In [17]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.linear_model import Perceptron
data = pd.read_csv("Audio_features.csv")
df=pd.DataFrame(data)
x=df.drop(['Id'],axis=1)
x.head()

Max_pitch  Avg_pitch      harmonic  percussive    chroma      mfccs  \
0  3997.841064  42.346413 -1.560000e-06   -0.000006  0.242919 -17.270573   
1  3990.921631  24.817791 -1.270000e-07   -0.000011  0.230322 -16.148429   
2  3998.479736  42.045082  2.510000e-07   -0.000007  0.236287 -16.326543   
3  3999.575439  44.815517  2.490000e-06    0.000003  0.253536 -16.116807   
4  3996.976074  33.027214 -4.280000e-07   -0.000011  0.247803 -15.478965   

    contrast      rolloff     zrate  Spectralcentroid Gender  
0  27.606991  4139.624091  0.072949       2061.120467      f  
1  27.869735  3797.619629  0.049481       1784.166438      f  
2  27.072397  3936.430742  0.069751       2022.862599      f  
3  27.384622  4116.783899  0.071112       2095.706138      f  
4  27.689376  3612.270115  0.064627       1830.020054      f

In [18]:
from sklearn.preprocessing import LabelEncoder
enc=LabelEncoder()
target=enc.fit_transform(df.Id)
x.Gender=enc.fit_transform(x.Gender)
y=target
x.head()

Max_pitch  Avg_pitch      harmonic  percussive    chroma      mfccs  \
0  3997.841064  42.346413 -1.560000e-06   -0.000006  0.242919 -17.270573   
1  3990.921631  24.817791 -1.270000e-07   -0.000011  0.230322 -16.148429   
2  3998.479736  42.045082  2.510000e-07   -0.000007  0.236287 -16.326543   
3  3999.575439  44.815517  2.490000e-06    0.000003  0.253536 -16.116807   
4  3996.976074  33.027214 -4.280000e-07   -0.000011  0.247803 -15.478965   

    contrast      rolloff     zrate  Spectralcentroid  Gender  
0  27.606991  4139.624091  0.072949       2061.120467       0  
1  27.869735  3797.619629  0.049481       1784.166438       0  
2  27.072397  3936.430742  0.069751       2022.862599       0  
3  27.384622  4116.783899  0.071112       2095.706138       0  
4  27.689376  3612.270115  0.064627       1830.020054       0

In [3]:
p = Perceptron(random_state=42,
              max_iter=10,
              tol=0.001)
p.fit(x, y)

Perceptron(alpha=0.0001, class_weight=None, eta0=1.0, fit_intercept=True,
      max_iter=10, n_iter=None, n_jobs=1, penalty=None, random_state=42,
      shuffle=True, tol=0.001, verbose=0, warm_start=False)

In [4]:
p.score(x,y)

0.020316027088036117

In [23]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(hidden_layer_sizes=(11, 3,2,39), random_state=10)
clf.fit(x, y) 

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(11, 3, 2, 39), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=20, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

In [24]:
print("weights between input and first hidden layer:")
print(clf.coefs_[0])
print("\nweights between first hidden and second hidden layer:")
print(clf.coefs_[1])

weights between input and first hidden layer:
[[ 3.10497971e-02  3.53990779e-01  3.47168190e-01  2.98045478e-01
  -2.63227251e-01  1.67832765e-01 -1.46877009e-02  6.33081228e-05
   1.50895641e-01 -1.87259515e-01 -6.94246026e-02]
 [ 1.67017974e-01  2.33866198e-01  3.03815234e-01  2.58261681e-01
  -2.62518291e-01 -4.30239678e-01  8.56058030e-02 -9.24168688e-02
  -2.69594848e-01  5.01121875e-01  2.50160010e-01]
 [ 7.30292397e-02 -2.99812237e-01  2.81080253e-01 -3.53449813e-03
   1.81915043e-02  3.00165329e-01 -4.94800465e-04 -1.23424823e-06
   4.03158866e-02  5.46321773e-02 -7.17678714e-02]
 [-3.13035551e-01  2.48556395e-01  2.44841189e-02 -8.81545614e-02
   1.77654972e-05 -1.26709428e-01 -4.58674538e-02  1.65917087e-02
   1.59079393e-03 -4.68003281e-02 -9.83513662e-03]
 [-3.13676694e-01  2.45973051e-02 -4.15077256e-01  7.07438374e-02
   1.42690367e-01 -3.91260084e-01  7.38495322e-02 -6.53915566e-03
   2.74694476e-01  4.49704682e-01  1.11268086e-01]
 [ 1.58273734e-01  2.34100463e-01  2.15

In [25]:
print("w0 = ", clf.coefs_[0][0][0])
print("w1 = ", clf.coefs_[0][1][0])

w0 =  0.03104979713213867
w1 =  0.1670179743744703


In [26]:
clf.coefs_[0][:,0]

array([ 0.0310498 ,  0.16701797,  0.07302924, -0.31303555, -0.31367669,
        0.15827373, -0.18667612,  0.10540103, -0.47089283, -0.14183996,
        0.10840492])

In [27]:
for i in range(len(clf.coefs_)):
    number_neurons_in_layer = clf.coefs_[i].shape[1]
    for j in range(number_neurons_in_layer):
        weights = clf.coefs_[i][:,j]
        print(i, j, weights, end=", ")
        print()
    print()

0 0 [ 0.0310498   0.16701797  0.07302924 -0.31303555 -0.31367669  0.15827373
 -0.18667612  0.10540103 -0.47089283 -0.14183996  0.10840492], 
0 1 [ 0.35399078  0.2338662  -0.29981224  0.2485564   0.02459731  0.23410046
 -0.27890798 -0.30342096 -0.46149889  0.27844858 -0.38607458], 
0 2 [ 0.34716819  0.30381523  0.28108025  0.02448412 -0.41507726  0.21575501
 -0.00213939  0.05078626  0.20501708 -0.18154536  0.16993583], 
0 3 [ 0.29804548  0.25826168 -0.0035345  -0.08815456  0.07074384 -0.04655703
 -0.46606226 -0.50257696  0.3236228  -0.182921   -0.29003125], 
0 4 [-2.63227251e-01 -2.62518291e-01  1.81915043e-02  1.77654972e-05
  1.42690367e-01  3.01599537e-05  1.82021521e-02  4.93301140e-02
 -2.63549978e-01 -3.19404200e-03  2.61913118e-01], 
0 5 [ 0.16783276 -0.43023968  0.30016533 -0.12670943 -0.39126008  0.03309009
  0.43211537 -0.24062079 -0.42593861 -0.14067125 -0.41629981], 
0 6 [-0.0146877   0.0856058  -0.0004948  -0.04586745  0.07384953 -0.26213451
  0.19798264 -0.14968299  0.1977

In [14]:
print("Bias values for first hidden layer:")
print(clf.intercepts_[0])
print("\nBias values for second hidden layer:")
print(clf.intercepts_[1])

Bias values for first hidden layer:
[ 0.52293624  0.5972168  -0.03214437  0.42403038 -0.30450325]

Bias values for second hidden layer:
[-0.79137859  0.63679598  0.43166974]


In [15]:
prob_results = clf.predict_proba([[0, 0], [0, 1], 
                                  [1, 0], [0, 1], 
                                  [1, 1], [2., 2.], 
                                  [1.3, 1.3], [2, 4.8]])
print(prob_results)

ValueError: shapes (8,2) and (11,5) not aligned: 2 (dim 1) != 11 (dim 0)

In [28]:
clf.score(x,y)

0.06217935563308024